services:
  postgresql:
    image: bitnami/postgresql:latest
    restart: always
    volumes:
      - ./:/app
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=main_psql_db
      - POSTGRES_USER=postgres
      - POSTGRESQL_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}

  pgadmin4:
    image: elestio/pgadmin:REL-9_5
    restart: always
    ports:
      - 8080:8080
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - PGADMIN_LISTEN_PORT=8080
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro
      - ./pgpassfile:/pgpassfile:ro
    depends_on:
      - postgresql
