services:
  postgresql:
    image: bitnami/postgresql:latest
    restart: always
    volumes:
      - pgdata:/bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}


  pgadmin4:
    image: elestio/pgadmin:REL-9_5
    restart: always
    ports:
      - 8080:8080
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
      - PGADMIN_LISTEN_PORT=8080
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro
      - ./pgpassfile:/pgpassfile:ro
    depends_on:
      - postgresql

  backend:
    build: ./backend
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./backend:/app

volumes:
  pgdata: