#cadvisor[v] grafana[] prometheus

#cadvisor collecting metrics about every container running

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    privileged: true #full host access
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    restart: always
    networks:
      - monitoring-vnet

  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro  
    networks:
      - monitoring-vnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-vnet
    depends_on:
      - prometheus
    
  flask-app:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - monitoring-vnet

networks:
  monitoring-vnet:
    driver: bridge
